services:
  filebrowser: # https://github.com/filebrowser/filebrowser
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./filebrowser_storage:/srv # Create first
      - filebrowser_db:/database

    # ports:
    #   - "8080:80" # Optional, for direct access without Traefik

    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.filebrowser.rule=Host(`files.harshbits.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=http"
      - "traefik.http.routers.filebrowser.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.filebrowser-secure.rule=Host(`files.harshbits.com`)"
      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
      - "traefik.http.routers.filebrowser-secure.tls=true"
      - "traefik.http.routers.filebrowser-secure.tls.certresolver=cloudflare"

      # Service
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

volumes:
  filebrowser_db:

networks:
  traefik:
    external: true