services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    # ports:
    #   - 8000:8000
    #   - 9000:9000
    restart: unless-stopped
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - traefik
    labels:
        - "traefik.enable=true"

        - "traefik.http.routers.portainer.rule=Host(`portainer.harshbits.com`)"
        - "traefik.http.routers.portainer.entrypoints=http"
        - "traefik.http.routers.portainer.middlewares=redirect-to-https"

        # HTTPS
        - "traefik.http.routers.portainer-secure.rule=Host(`portainer.harshbits.com`)"
        - "traefik.http.routers.portainer-secure.entrypoints=https"
        - "traefik.http.routers.portainer-secure.tls=true"
        - "traefik.http.routers.portainer-secure.tls.certresolver=cloudflare"

        - "traefik.docker.network=traefik"

        # Service
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik:
    external: true